### PR TITLE
Cargo: bump git to 0.13

### PR DESCRIPTION
**Pull request by steveeJ**

### CODE REVIEW

**Comment by lukaslueg** [comment]
Thanks. Should be fine to bump to `0.13` instead of `0.13.2`, shouldn't it

**Comment by lukaslueg** [comment]
Thanks. Do you need a bump?

**Comment by steveeJ** [comment]
> Thanks. Do you need a bump?

Would be nice!

**Comment by lukaslueg** [comment]
Bumped

**Pull request merged**
