### PR TITLE
No need to specify 'build.rs' in Cargo.toml anymore

### PR DESCRIPTION
**Pull request by bbigras**
I'm pretty sure we don't need to specify the build.rs file anymore.

### CODE REVIEW

**Comment by lukaslueg** [comment]
Thanks for the PR! Yes, the manifest-key is not needed since a few version back. However, I'd like to keep it in place, since the file just being there and acting on the compilation process feels a little like spooky action at a distance. This is just personal taste, yet I'd like to leave this bit in.

**Comment by xftroxgpx** [comment]
@lukaslueg Completely unrelated, but would really like to know your take on one of my pet peeves, or whether or not the following qualifies as `spooky action at a distance`, from [here](
https://doc.rust-lang.org/book/2018-edition/ch04-01-what-is-ownership.html#ways-variables-and-data-interact-move):
`let somevar=someothervar` sometimes does copy, sometimes does move - of `someothervar`.
screenshot_2018-11-05_20-51-59

<details><summary></summary>
(and please do not take this as an attack, in any way; saying it because I'm aware this is very unusual to ask in this context and I don't want anyone to get the wrong impression)
</details>

**Comment by lukaslueg** [comment]
Well, yes and no. If a type implements `Copy` or not is entirely left to the owner of that type, you can't retroactively bolt it on. If your type is very simple and basically free, it might be advantageous to impl `Copy` just because of ease of use. Notice however that the compiler from then on is free to copy an instance if it can't move it, which might end up being very costly because it's not readily apparent that `let somevar = someothervar` is no longer free. You probably want to think of `Copy` as you might think of `Deref`: If you are not sure if you should implement it, you should not.

**Comment by xftroxgpx** [comment]
> the compiler from then on is free to copy an instance if it can't move it

I don't understand what you meant here. 
Doesn't the compiler give a compile error if it can't move it? assuming it's non-`Copy`, because if it's `Copy` it'll always be copied instead of moved (or so is my understanding so far).

I'm definitely not implementing `Copy`, in fact I'm going to try to make sure all my vars are non-Copy (but not sure if I can do that, I don't know enough Rust to know if I can) by wrapping them into a struct type like 
```rust
#[derive(Clone,Debug)]
struct WrappedI32(i32);
...
let someothervar:WrappedI32 = WrappedI32(5);
let somevar = someothervar.clone(); //explicit copy, if I want copy, OR
let somevar = someothervar; //implicit move, since I'm unlikely to ever want copy.
```
Because how else am I gonna differentiate copy and move? :D
But as I said, I don't yet know enough Rust to see where else this might bite me (function args? refs, match? I don't know - I'm reading the book...)

**Comment by lukaslueg** [comment]
I was referring to the fact that both `Copy` and non-`Copy` types may or may not have their underlying representation actually copied in memory. If your type is non-`Copy`, you'll get a compile-error if it's moved and then accessed. If your type is `Copy`, the compiler does not enforce move-semantics (because there is the escape hatch of just copying it); yet it might be able to optimize away the actual copy if your code is just moving the instance.

I'm under the impression that you are worrying too much about `Copy`. Almost all non-trivial types you'll ever see are not `Copy`. Simple types like `i32` are `Copy` because it's dead-cheap. Given that a type of yours is or can be `Clone` you can derive `Copy`for it. For example, you may make a type like `enum Color { WineRed, SkyBlue, GrassGreen, RGB(u8, u8, u8) }` to be `Copy` if it's ubiquitous and there is little chance of confusion.

`reddit/rust` is probably a better forum to ask a comprehensive question.

**Comment by xftroxgpx** [comment]
Thanks @lukaslueg! Much appreciated! Cheers

**Pull request closed without merging**
