### PR TITLE
Change OPT_LEVEL to be &str instead of u8.

### LINKED ISSUE #15: Optimisation level might not be an integer
Currently `OPT_LEVEL` has type `u8` but if it's set to `s` or `z` then the generated built.rs won't build:

```
   |
35 | pub const OPT_LEVEL: u8 = z;
   |                           ^ not found in this scope
```

Maybe it should be a string instead?

### PR DESCRIPTION
**Pull request by adamgreig**
Closes #15.

This builds and passes tests and seems to do what you'd expect. Let me know if you'd like me to bump the version number in Cargo.toml.

### CODE REVIEW

**Comment by lukaslueg** [comment]
Thanks! Could you bump to 0.3, as this is a breaking change?

**Comment by lukaslueg** [comment]
Thanks

**Comment by lukaslueg** [comment]
In case you need this, I've published it as 0.3

**Comment by adamgreig** [comment]
Great, thank you!

**Pull request merged**
